### ISSUE TITLE
Production grade Flask deployment

### ISSUE THREAD

**Issue by djixyacine** [elixir-europe/proTES#1]
**Is your feature request related to a problem? Please describe.**
The current Flask application is not production grade, and should be used for development environments only.

**Describe the solution you'd like**
Re-structure the proTES code base in order to support running a Gunicorn app on top of Flask.

**Comment by uniqueg** [comment]
Compare and handle analogous to elixir-europe/WES-ELIXIR/issues/80

**Comment by uniqueg** [comment]
Seems to be done already
