### ISSUE TITLE
Fix naming of TES task request objects

### ISSUE THREAD

**Issue by Ayush5120** [elixir-europe/proTES#137]
**Description** :

- The Tes task request, when forwarded to `proTES`, undergoes certain operations on the request body such as updating the task state, adding a task identifier, logging information, and specifying the TES endpoint where the task is forwarded, etc. All of these operations are currently performed on the `task_incoming` object, which is an instance of the `TesTask` class and where the final results of the executed task are stored.

- The `task_outgoing` object, on the other hand, is used to save and store the incoming request in the database without modifying it. This is done to keep a record of what the client had originally passed when the task was received.

**Problem** : 

- The naming of TES task requests, that is `task_incoming` and `task_outgoing` is currently confusing.

**Solution** :

- Rather than using the terms `task_incoming`and `task_outgoing`, it may be more appropriate to refer to one as simply `task` and the other as `task_original`. The `task` copy would be the working version that gets modified and retains all the necessary information to be returned to the user or client, while the `task_original` would be the one that remains unchanged.

**Comment by BYZANTINE26** [comment]
Hi, 

I have gone through the Description and Solution of your issue, and understood the code base. 
I have identified 3 files where changes need to be made for task_incoming: `pro_tes\ga4gh\tes\models.py`, `pro_tes\ga4gh\tes\task_runs.py` and `pro_tes\tasks\track_task_progress.py`

For task_outgoing: `pro_tes\ga4gh\tes\models.py` and `pro_tes\ga4gh\tes\task_runs.py`

I request you to assign this issue to me.

Thanks

**Comment by Ayush5120** [comment]
Thanks, @BYZANTINE26, Please read the contributor guidelines before and you are ready to go, I am assigning this to you.
