### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by uniqueg** [elixir-europe/proTES#15]
**Is your feature request related to a problem? Please describe.**

Add extensive unit tests for the entire app.

**Describe the solution you'd like**

Write unit tests (preferentially using [`pytest`](https://docs.pytest.org/en/7.2.x/)) for every class/method/function, aiming for 100% code coverage.

**Describe alternatives you've considered**
N/A

**Comment by uniqueg** [comment]
This can also be addressed iteratively, module by module, and can therefore be assigned to multiple people. In that case, open a separate issue for the module that you want to write tests for and link to this issue.

**Comment by SohamRatnaparkhi** [comment]
Hi @uniqueg ,
I would love to work on this issue.  I have prior experience using Pytest and am willing to learn new techniques as needed.
Thank you

**Comment by uniqueg** [comment]
Thanks @SohamRatnaparkhi. Given that there's a lot of code that needs to be tested, I would suggest that you pick one module and open an issue for that and link it here. We can then assign you to that issue.
