### ISSUE TITLE
Use environment variables for MongoDB and RabbitMQ

### ISSUE THREAD

**Issue by djixyacine** [elixir-europe/proTES#2]
**Is your feature request related to a problem? Please describe.**
MongoDB and RabbitMQ are currently hard coded in the YAMLs under pro_tes/config.
This makes dynamic deployments on OpenShift/K8S environments impossible.

**Describe the solution you'd like**
Source the MongoDB and RabbitMQ variable from environment variables, while using the hard coded ones as defaults.

**Comment by uniqueg** [comment]
Implement analogous to elixir-europe/WES-ELIXIR/pull/86

**Comment by uniqueg** [comment]
Was already done.
