### ISSUE TITLE
Deploy at CSC

### ISSUE THREAD

**Issue by uniqueg** [elixir-europe/proTES#36]
**Is your feature request related to a problem? Please describe.**

For implementing an end-to-end test of [WES-ELIXIR](https://github.com/elixir-europe/WES-ELIXIR) > [proTES](https://github.com/elixir-europe/proTES) > [TEStribute](https://github.com/elixir-europe/TEStribute) > [TESK](https://github.com/elixir-europe/https://github.com/EMBL-EBI-TSI/TESK) or [mock-TES](https://github.com/elixir-europe/mock-TES), instances of all services should be deployed in a publicly accessible location.

**Describe the solution you'd like**

Use `docker-compose` to deploy service at VM provided by CSC Finland.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by shukapoo** [comment]
ProTes deployed at : http://86.50.252.55:7878/ga4gh/tes/v1/ui/

**Comment by uniqueg** [comment]
Thanks a lot! Seems to be working. Will close for now. If further tests require changes in deployment, I would re-open
