### ISSUE TITLE
Allow users to configure security definitions 

### ISSUE THREAD

**Issue by robertopreste** [elixir-europe/proTES#50]
**Is your feature request related to a problem? Please describe.**
If I want to build proTES without providing (or providing at a later time) an OpenAPI file, I won't be able to do it because it is currently required in [app.py](https://github.com/elixir-cloud-aai/proTES/blob/6a005f30bd69801d43a1469d97674befc76c796a/pro_tes/app.py#L39), since `add_security_definitions=True`.

**Describe the solution you'd like**
A very easy solution to this would be to get that flag from the [app_config.yaml](https://github.com/elixir-cloud-aai/proTES/blob/6a005f30bd69801d43a1469d97674befc76c796a/pro_tes/config/app_config.yaml#L11) file, where the `authorization_required` key is already available, thus changing the above-mentioned line in app.py to `add_security_definitions=get_conf(config, 'security', 'authorization_required')`. 
This is consistent with what is done for other arguments of `register_openapi`.

**Describe alternatives you've considered**
At the moment I'm solving this by simply replacing the original `app.py` file with my own version that has that simple code change already in place, but it is quite annoying. 

**Additional context**
N/A

**Comment by uniqueg** [comment]
Thanks for the suggestion and detailed feature request. It's a good idea!

We are working hard for preparing for a [COVID-19 virtual hackathon](https://github.com/virtual-biohackathons/covid-19-bh20/wiki) that's gonna take place in the second week of April (perhaps you are interested?). Not sure if I will be able to do it before after that is concluded. Possibly someone else will, but no guarantees. If you'd rather have it sooner, you are very welcome to file a PR and assign me as reviewer. I'll surely merge this.

**Comment by robertopreste** [comment]
Sure, I'm happy to open a PR for that, it's an easy fix. Thanks for your availability, and for sharing the hackathon, will surely have a look at that!
