### ISSUE TITLE
Replace boilerplate code with FOCA archetype

### ISSUE THREAD

**Issue by sarthakgupta072** [elixir-europe/proTES#55]
A lot of the code shared between this service and others in the organizationhas been moved to the [FOCA](https://github.com/elixir-cloud-aai/foca) archetype.

Duplicate code should be removed from this service and, where necessary, the remaining code should be refactored to make use of FOCA.

**Comment by vipulchhabra99** [comment]
I am interested in taking up this issue next. Can you please assign me this issue? @uniqueg @sarthakgupta072

**Comment by sarthakgupta072** [comment]
Assigned @vipulchhabra99 👍🏼

**Comment by anuragxxd** [comment]
If @vipulchhabra99 is not working on this maybe I cn work on this @uniqueg @sarthakgupta072 as I have also done kind off same work in proWes.

**Comment by vipulchhabra99** [comment]
@git-anurag-hub I am currently working on it and about to complete it.

**Comment by anuragxxd** [comment]
Np @vipulchhabra99 . Great

**Comment by uniqueg** [comment]
Closed by #71
